### ISSUE TITLE
Inquiry About Hyperparameters for Datasets

### ISSUE THREAD

**Issue by kennethyangg** [vsuarezpaniagua/3-phase_finetuning#1]
Thank you for your excellent work! I have been going through it and found it very insightful.

I was wondering if the optimal set of hyperparameters for each dataset is provided somewhere, or if you have any recommendations on the best configuration to use?

Thank you so much for your time and help!

Best regards,
Kenneth

**Comment by Alejo-LA** [comment]
Hi Yang Hsu. You can find the hyperparameters used for each one of the datasets in Table A.1 in the paper's Appendix. I guess the seeds were not fixed. So you may find slightly different results.

Page 11: https://arxiv.org/pdf/2405.14437

Please let me know if you have more questions.

Kind regards,
Alejo

**Comment by Alejo-LA** [comment]
This is the table:

**Comment by kennethyangg** [comment]
Got it! Appreciate the reply!
